---
title: "MP_02_datavis"
author: "William Smithers"
date: "`r Sys.Date()`"
format: html
code-fold: true
warning: false
editor: visual
self-contained: true
---

**Mini-Project 2: Data Visualization**


```{r setup, echo=FALSE, include=FALSE}
library(tidyverse)
library(readr)
taylor_songs <- read_csv("~/Downloads/taylor_all_songs.csv")
```

```{r, fig.cap="Using mean acousticness to expain mean daceability. An analysis of Taylor Swift's albums yeilds a negative relationship between mean daceability and mean acousticness, evidenced with a correlation coefficient of -0.23."}
filtered_songs <- taylor_songs %>%
  filter(ep == FALSE, bonus_track == FALSE, is.na(promotional_release), is.na(single_release))

album_means <- filtered_songs %>%
  group_by(album_name) %>%
  summarise(mean_acousticness = mean(acousticness, na.rm = TRUE),
            mean_danceability = mean(danceability, na.rm = TRUE))

cor_coefficient <- cor(album_means$mean_acousticness, album_means$mean_danceability, use = "complete.obs")

ggplot(album_means, aes(x = mean_acousticness, y = mean_danceability, label = album_name)) +
  geom_point() +
  geom_text(nudge_x = 0.01, nudge_y = 0.01, check_overlap = FALSE) +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  labs(title = "Understanding Daceability through Acousticness: Taylor's Negative Tale",
       x = "Mean Acousticness",
       y = "",
       subtitle = "Mean Danceability") +
  theme_minimal() +
#  scale_color_viridis_d(option = "bviridis")+
  theme(legend.position = "none")+

  annotate("text", x = min(album_means$mean_acousticness), y = min(album_means$mean_danceability) - 0.05, 
           label = paste("Correlation Coefficient: ", round(cor_coefficient, 2)), 
           hjust = 0, size = 3.5, color = 'darkblue')

```

